import {
  DEFAULT_NUTRITION_GOALS,
  sumTotals,
  type FoodEntry,
  type NutritionGoals,
} from '@input_output/shared'
import type { MetricConfig } from '../components/MetricCard'

const fmtInt = (n: number) => n.toLocaleString()

export function buildMetricConfigs(
  entries: readonly FoodEntry[],
  goals: NutritionGoals = DEFAULT_NUTRITION_GOALS,
): MetricConfig[] {
  const totals = sumTotals(entries)

  return [
    {
      label: 'Calories',
      value: totals.calories,
      formatValue: fmtInt,
      unit: null,
      goal: goals.calories.value,
      formatGoal: fmtInt,
      color: '#ea580c',
      iconBg: '#fbf1e8',
      iconClass: 'fa-fire',
      // Data-series gradient (not brand primary) — orange → teal energy spectrum
      gradient: 'linear-gradient(to right, #0f766e, #14b8a6)',
      rightLabel: 'of daily goal',
      remainingSuffix: 'kcal',
      remaining: (v, g) => `${Math.max(g - v, 0).toLocaleString()} kcal`,
    },
    {
      label: 'Protein',
      value: totals.protein,
      formatValue: (n) => `${n}`,
      unit: 'g',
      goal: goals.protein.value,
      formatGoal: (n) => `${n}`,
      color: '#059669',
      iconBg: '#eef7f2',
      iconClass: 'fa-dumbbell',
      gradient: 'linear-gradient(to right, #059669, #14b8a6)',
      rightLabel: 'of daily goal',
      remainingSuffix: 'g',
      remaining: (v, g) => `${Math.max(g - v, 0)} g`,
    },
    {
      label: 'Carbs',
      value: totals.carbs,
      formatValue: (n) => `${n}`,
      unit: 'g',
      goal: goals.carbs.value,
      formatGoal: (n) => `${n}`,
      color: '#d97706',
      iconBg: '#fbf7ee',
      iconClass: 'fa-wheat-awn',
      gradient: 'linear-gradient(to right, #d97706, #fbbf24)',
      rightLabel: 'of daily goal',
      remainingSuffix: 'g',
      remaining: (v, g) => `${Math.max(g - v, 0)} g`,
    },
    {
      label: 'Fat',
      value: totals.fat,
      formatValue: (n) => `${n}`,
      unit: 'g',
      goal: goals.fat.value,
      formatGoal: (n) => `${n}`,
      color: '#db2777',
      iconBg: '#faf0f5',
      iconClass: 'fa-bacon',
      gradient: 'linear-gradient(to right, #db2777, #f472b6)',
      rightLabel: 'of daily goal',
      remainingSuffix: 'g',
      remaining: (v, g) => `${Math.max(g - v, 0)} g`,
    },
    {
      label: 'Fiber',
      value: totals.fiber,
      formatValue: (n) => `${n}`,
      unit: 'g',
      goal: goals.fiber.value,
      formatGoal: (n) => `${n}`,
      color: '#65a30d',
      iconBg: '#f3f8eb',
      iconClass: 'fa-seedling',
      gradient: 'linear-gradient(to right, #65a30d, #a3e635)',
      rightLabel: 'of daily goal',
      remainingSuffix: 'g',
      remaining: (v, g) => `${Math.max(g - v, 0)} g`,
    },
    {
      label: 'Caffeine',
      value: totals.caffeine,
      formatValue: (n) => `${n}`,
      unit: 'mg',
      goal: goals.caffeine.value,
      formatGoal: (n) => `${n}`,
      color: '#7c3aed',
      iconBg: '#f3f0fa',
      iconClass: 'fa-mug-hot',
      gradient: 'linear-gradient(to right, #7c3aed, #a78bfa)',
      rightLabel: 'of daily limit',
      remainingSuffix: 'mg',
      remaining: (v, g) => `${Math.max(g - v, 0)} mg`,
    },
  ]
}